export const commonStrings = {
  en: {
    welcome: 'Welcome',
    startWithSocial: 'Get started easily with your social account',
    github: 'Continue with GitHub',
    google: 'Continue with Google',
    terms: 'By continuing, you agree to our Terms of Service and Privacy Policy.',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    korean: '한국어',
    english: 'English',
    channels: 'Channels',
    categories: 'Categories',
    favorites: 'Favorites',
    favoritesEmpty: 'No favourite channels yet.',
    createCategory: 'Create Category',
    inviteMembers: 'Invite Members',
    createNewWorkspace: 'Create New Workspace',
    dashboard: 'Dashboard',
    search: 'Search',
    directMessages: 'Direct Messages',
    appConnect: 'App Connect',
    online: 'Online',
    offline: 'Offline',
    directory: 'Directory',
    inbox: 'Inbox',
    unreadCount: '{{count}}',
    unreadCountMax: '99+',
    statusLabels: {
      online: 'Online',
      offline: 'Offline',
      away: 'Away',
      busy: 'Do not disturb',
    },
    copy: {
      copy: 'Copy',
      copied: 'Copied!',
    },
  },
  ko: {
    welcome: '환영합니다',
    startWithSocial: '소셜 계정으로 간편하게 시작하세요',
    github: 'GitHub으로 계속하기',
    google: 'Google로 계속하기',
    terms: '계속 진행하시면 서비스 약관 및 개인정보 처리방침에 동의하는 것으로 간주됩니다.',
    termsOfService: '서비스 약관',
    privacyPolicy: '개인정보 처리방침',
    korean: '한국어',
    english: 'English',
    channels: '채널',
    categories: '카테고리',
    favorites: '즐겨찾기',
    favoritesEmpty: '즐겨찾기한 채널이 없습니다.',
    createCategory: '카테고리 만들기',
    inviteMembers: '멤버 초대하기',
    createNewWorkspace: '새 워크스페이스 생성',
    dashboard: '대시보드',
    search: '검색',
    directMessages: '다이렉트 메시지',
    appConnect: '앱 커넥트',
    online: '온라인',
    offline: '오프라인',
    directory: '디렉토리',
    inbox: '수신함',
    unreadCount: '{{count}}',
    unreadCountMax: '99+',
    statusLabels: {
      online: '온라인',
      offline: '오프라인',
      away: '자리비움',
      busy: '방해 금지',
    },
    copy: {
      copy: '복사',
      copied: '복사됨',
    },
  },
  ja: {
    welcome: 'ようこそ',
    startWithSocial: 'ソーシャルアカウントで簡単に始めましょう',
    github: 'GitHubで続行',
    google: 'Googleで続行',
    terms: '続行することで、利用規約とプライバシーポリシーに同意したものとみなされます。',
    termsOfService: '利用規約',
    privacyPolicy: 'プライバシーポリシー',
    korean: '한국어',
    english: 'English',
    channels: 'チャンネル',
    categories: 'カテゴリ',
    favorites: 'お気に入り',
    favoritesEmpty: 'お気に入りのチャンネルがありません。',
    createCategory: 'カテゴリを作成',
    inviteMembers: 'メンバーを招待',
    createNewWorkspace: '新しいワークスペースを作成',
    dashboard: 'ダッシュボード',
    search: '検索',
    directMessages: 'ダイレクトメッセージ',
    appConnect: 'アプリ接続',
    online: 'オンライン',
    offline: 'オフライン',
    directory: 'ディレクトリ',
    inbox: '受信トレイ',
    unreadCount: '{{count}}',
    unreadCountMax: '99+',
    statusLabels: {
      online: 'オンライン',
      offline: 'オフライン',
      away: '退席中',
      busy: '取り込み中',
    },
    copy: {
      copy: 'コピー',
      copied: 'コピーしました',
    },
  },
  fr: {
    welcome: 'Bienvenue',
    startWithSocial: 'Commencez facilement avec votre compte social',
    github: 'Continuer avec GitHub',
    google: 'Continuer avec Google',
    terms: 'En continuant, vous acceptez nos Conditions d\'utilisation et notre Politique de confidentialité.',
    termsOfService: 'Conditions d\'utilisation',
    privacyPolicy: 'Politique de confidentialité',
    korean: '한국어',
    english: 'English',
    channels: 'Canaux',
    categories: 'Catégories',
    favorites: 'Favoris',
    favoritesEmpty: 'Aucun canal favori pour le moment.',
    createCategory: 'Créer une catégorie',
    inviteMembers: 'Inviter des membres',
    createNewWorkspace: 'Créer un nouvel espace de travail',
    dashboard: 'Tableau de bord',
    search: 'Rechercher',
    directMessages: 'Messages directs',
    appConnect: 'Connexion d\'applications',
    online: 'En ligne',
    offline: 'Hors ligne',
    directory: 'Annuaire',
    inbox: 'Boîte de réception',
    unreadCount: '{{count}}',
    unreadCountMax: '99+',
    statusLabels: {
      online: 'En ligne',
      offline: 'Hors ligne',
      away: 'Absent',
      busy: 'Ne pas déranger',
    },
    copy: {
      copy: 'Copier',
      copied: 'Copié !',
    },
  },
};

export default commonStrings;
