export const messageStrings = {
  en: {
    actions: {
      copy: 'Copy',
      react: 'Add reaction',
      reply: 'Reply',
      translate: 'Translate',
      forward: 'Forward',
      pin: 'Pin message',
      unpin: 'Unpin message',
      startThread: 'Start thread',
      edit: 'Edit',
      delete: 'Delete',
      more: 'More',
    },
    translated: 'Translated from {{lang}}',
    translating: 'Translating...',
    translationNotice: 'This message was translated.',
    showOriginal: 'View original',
    hideOriginal: 'Hide original',
    forwardTo: 'Forward to',
    forwardSuccess: 'Message forwarded',
  },
  ko: {
    actions: {
      copy: '복사',
      react: '반응 추가',
      reply: '답글',
      translate: '번역하기',
      forward: '전달하기',
      pin: '고정하기',
      unpin: '고정 해제',
      startThread: '스레드 시작',
      edit: '수정하기',
      delete: '삭제하기',
      more: '더보기',
    },
    translated: '{{lang}}에서 번역됨',
    translating: '번역 중...',
    translationNotice: '이 문장은 번역되었습니다.',
    showOriginal: '원문보기',
    hideOriginal: '원문 숨기기',
    forwardTo: '전달할 위치',
    forwardSuccess: '메시지가 전달되었습니다',
  },
};

export default messageStrings;
