export const mockNotifications = [
  {
    id: 'notif-1',
    type: 'mention',
    title: 'Alice Kim mentioned you in #design',
    message: '@you Can you review the new mockups?',
    workspaceId: 'ws1',
    channelId: 'c1',
    senderId: 'u2',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    read: false,
    important: true,
  },
  {
    id: 'notif-2',
    type: 'reply',
    title: 'Bob Lee replied to your thread',
    message: 'Thanks for the feedback! I\'ll update it.',
    workspaceId: 'ws1',
    channelId: 'c2',
    senderId: 'u3',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    read: false,
    important: false,
  },
  {
    id: 'notif-3',
    type: 'dm',
    title: 'New direct message from Charlie Park',
    message: 'Hey, do you have a moment to chat?',
    workspaceId: 'ws1',
    channelId: 'dm-u4',
    senderId: 'u4',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    read: false,
    important: true,
  },
  {
    id: 'notif-4',
    type: 'workspace',
    title: 'You were added to Design Team workspace',
    message: 'Alice Kim added you to Design Team',
    workspaceId: 'ws2',
    channelId: null,
    senderId: 'u2',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    read: true,
    important: false,
  },
  {
    id: 'notif-5',
    type: 'channel',
    title: 'New channel: #product-launch',
    message: 'A new channel was created',
    workspaceId: 'ws1',
    channelId: 'c5',
    senderId: 'u2',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    read: true,
    important: false,
  },
];
