export const strings = {
  en: {
    welcome: 'Welcome',
    startWithSocial: 'Get started easily with your social account',
    github: 'Continue with GitHub',
    google: 'Continue with Google',
    terms: 'By continuing, you agree to our Terms of Service and Privacy Policy.',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    korean: '한국어',
    english: 'English',
    channels: 'Channels',
    categories: 'Categories',
    favorites: 'Favorites',
    favoritesEmpty: 'No favourite channels yet.',
    createCategory: 'Create Category',
    inviteMembers: 'Invite Members',
    createNewWorkspace: 'Create New Workspace',
    dashboard: 'Dashboard',
    search: 'Search',
    directMessages: 'Direct Messages',
    appConnect: 'App Connect',
    online: 'Online',
    offline: 'Offline',
    directory: 'Directory',
    inbox: 'Inbox',
    unreadCount: '{{count}}',
    unreadCountMax: '99+',
    statusLabels: {
      online: 'Online',
      offline: 'Offline',
      away: 'Away',
      busy: 'Do not disturb',
    },
    copy: {
      copy: 'Copy',
      copied: 'Copied!',
    },
    modals: {
      titles: {
        search: 'Search in Channel',
        members: 'Members',
        pinned: 'Pinned Messages',
        threads: 'Threads',
        info: 'Channel Info',
        notifications: 'Notifications',
        createCategory: 'Create Category',
        inviteMember: 'Invite member',
        inviteGuest: 'Invite guest',
        inviteResult: 'Invitation summary',
        fileUpload: 'Upload Files',
        channelFiles: 'Channel Files',
        mention: 'Mention',
        addChannel: 'Add Channel',
        addDM: 'Start a DM',
        addApp: 'Add App',
        addFavorite: 'Manage Favorites',
      },
      addChannel: {
        description: 'Add a new channel to {{category}}.',
        nameLabel: 'Channel name',
        namePlaceholder: 'e.g. design-review',
        descLabel: 'Description',
        descPlaceholder: 'Briefly describe the purpose of this channel.',
        submit: 'Create channel',
      },
      addDM: {
        searchLabel: 'Search members',
        searchPlaceholder: 'Find by name or email',
        empty: 'No additional members available.',
      },
      addApp: {
        description: 'Connect apps to your workspace.',
        addButton: 'Add',
        empty: 'No apps available.',
        itemDescription: 'Keep your favourite tools in sync.',
      },
      addFavorite: {
        description: 'Choose which channels should appear in your favourites.',
        add: 'Add to favourites',
        remove: 'Remove from favourites',
        empty: 'No channels available.',
      },
      inviteMember: {
        description: 'Invite teammates by email or share a time-bound invite link.',
        tabs: {
          direct: 'Invite by email',
          link: 'Generate invite link',
        },
        email: {
          searchLabel: 'Search teammate email',
          searchPlaceholder: 'Enter a name or email address',
          emptySelection: 'No recipients selected.',
          groupLabel: 'Assign to groups',
          sendButton: 'Send invites',
          successTitle: 'Invitations sent',
          successSubtitle: 'Each teammate receives a personalised, traceable link.',
          copyLink: 'Copy invite link',
        },
        link: {
          description: 'Configure expiration and usage limits before sharing.',
          expirationLabel: 'Expiration',
          expirationOptions: {
            '24h': '24 hours',
            '7d': '7 days',
            '30d': '30 days',
            never: 'No expiration',
          },
          usageLabel: 'Usage limit',
          usageOptions: {
            '1': '1 use',
            '5': '5 uses',
            '10': '10 uses',
            '50': '50 uses',
            unlimited: 'Unlimited',
            single: '1 use',
          },
          generateButton: 'Generate invite link',
          copyButton: 'Copy link',
          successTitle: 'Invite link ready',
          successSubtitle: 'Share this link with your team.',
        },
        history: {
          title: 'Invite link history',
          empty: 'No invite links generated yet.',
          created: 'Created',
          expires: 'Expires',
          usage: 'Usage limit',
        },
      },
      inviteGuest: {
        description: 'Invite guests to {{channel}} or generate a time-bound guest link.',
        tabs: {
          direct: 'Invite by email',
          link: 'Generate guest link',
        },
        email: {
          searchLabel: 'Search guest email',
          searchPlaceholder: 'Enter a guest email address',
          emptySelection: 'No guests selected.',
          sendButton: 'Send guest invites',
          successTitle: 'Guest invitations sent',
          successSubtitle: 'Guests can join via the personalised link below.',
          copyLink: 'Copy guest link',
        },
        link: {
          description: 'Configure expiration and usage limits before sharing.',
          expirationLabel: 'Expiration',
          expirationOptions: {
            '24h': '24 hours',
            '7d': '7 days',
            '30d': '30 days',
            never: 'No expiration',
          },
          usageLabel: 'Usage limit',
          usageOptions: {
            '1': '1 use',
            '5': '5 uses',
            '10': '10 uses',
            '50': '50 uses',
            unlimited: 'Unlimited',
            single: '1 use',
          },
          generateButton: 'Generate guest link',
          copyButton: 'Copy link',
          successTitle: 'Guest link ready',
          successSubtitle: 'Share this link with external collaborators.',
        },
        history: {
          title: 'Guest link history',
          empty: 'No guest links generated yet.',
          created: 'Created',
          expires: 'Expires',
          usage: 'Usage limit',
        },
        context: {
          channelPrefix: 'Channel',
        },
      },
      members: {
        inviteGuestButton: 'Invite guest to channel',
      },
      inviteResult: {
        title: 'Invitation summary',
        memberDescription: 'The following teammates received invite emails with unique links.',
        guestDescription: 'The following guests received invite emails with unique links.',
        linkDescription: 'Share this link with anyone who should join.',
        close: 'Close',
        codeLabel: 'Code',
        createdLabel: 'Created',
      },
      inbox: {
        title: 'Inbox',
        empty: 'No notifications yet.',
        tabs: {
          all: 'All',
          important: 'Important',
          byWorkspace: 'By Workspace',
        },
        actions: {
          markAsRead: 'Mark as read',
          delete: 'Delete',
          markAllRead: 'Mark all as read',
        },
        filters: {
          unreadOnly: 'Unread only',
          showAll: 'Show all',
        },
      },
      workspaceProfile: {
        title: 'Workspace Profile',
        description: 'Set your profile for this workspace.',
        displayName: 'Display name',
        statusMessage: 'Status message',
        avatar: 'Avatar',
        saveButton: 'Save changes',
      },
      deactivateAccount: {
        title: 'Deactivate Account',
        description: 'Are you sure you want to deactivate your account? Your data will be preserved but you won\'t be able to access it.',
        confirmButton: 'Deactivate',
        cancelButton: 'Cancel',
        warning: 'This action can be reversed by contacting support.',
      },
      deleteAccount: {
        title: 'Delete Account',
        description: 'Are you sure you want to permanently delete your account? This action cannot be undone.',
        confirmButton: 'Delete permanently',
        cancelButton: 'Cancel',
        warning: 'All your data, messages, and workspaces will be permanently removed.',
        typeToConfirm: 'Type "DELETE" to confirm',
        confirmPlaceholder: 'DELETE',
      },
    },
    message: {
      actions: {
        copy: 'Copy',
        react: 'Add reaction',
        reply: 'Reply',
        translate: 'Translate',
        forward: 'Forward',
        pin: 'Pin message',
        unpin: 'Unpin message',
        startThread: 'Start thread',
        edit: 'Edit',
        delete: 'Delete',
        more: 'More',
      },
      translated: 'Translated from {{lang}}',
      translating: 'Translating...',
      translationNotice: 'This message was translated.',
      showOriginal: 'View original',
      hideOriginal: 'Hide original',
      forwardTo: 'Forward to',
      forwardSuccess: 'Message forwarded',
    },
    workspace: {
      settings: 'Workspace Settings',
      create: 'Create Workspace',
      joinWithLink: 'Join with invite link',
      inviteCodePlaceholder: 'Enter invite code',
      joinButton: 'Join Workspace',
    },
    directory: {
      title: 'Directory',
      searchPlaceholder: 'Search members...',
      sortLabel: 'Sort',
      sortOptions: {
        nameAsc: 'Name A-Z',
        joinDesc: 'Newest members',
        roleAsc: 'Role',
        status: 'Status',
      },
      pageSizeLabel: 'Rows per page',
      pagination: {
        previous: 'Previous',
        next: 'Next',
        summary: 'Showing {{from}}-{{to}} of {{total}} members',
      },
      columns: {
        name: 'Member',
        email: 'Email',
        provider: 'Provider',
        joinedAt: 'Joined',
        group: 'Group',
        role: 'Role',
        status: 'Status',
      },
      empty: 'No members found.',
    },
    userSettings: {
      title: 'User settings',
      navProfile: 'Profile',
      navPreferences: 'Preferences',
      navLogout: 'Log out',
      navDevices: 'Signed-in devices',
      profile: {
        title: 'My profile',
        description: 'Update your avatar and basic information.',
        deactivateTitle: 'Deactivate account',
        deactivateDescription: 'Temporarily disable access while preserving your data.',
        deactivateButton: 'Deactivate account',
        deleteTitle: 'Delete account',
        deleteDescription: 'Permanently remove your account and associated data.',
        deleteButton: 'Delete account',
        nameLabel: 'Real name',
        emailLabel: 'Email',
        socialLoginLabel: 'Social login',
        socialLoginSuffix: 'signed up with this provider',
        avatarChange: 'Change avatar',
        saveButton: 'Save changes',
      },
      account: {
        title: 'Workspace memberships',
        description: 'You belong to the following workspaces.',
        workspaceColumn: 'Workspace',
        roleColumn: 'Role',
        joinedColumn: 'Joined',
        empty: 'No workspace memberships found.',
      },
      logout: {
        title: 'Sign out',
        description: 'End your current session on this device.',
        button: 'Log out',
        modalTitle: 'Log out of Prizm?',
        modalDescription: 'You can always sign back in. Unsaved changes may be lost.',
        confirm: 'Log out',
        cancel: 'Cancel',
        inProgress: 'Signing out...',
      },
      preferences: {
        notifications: {
          title: 'Notification settings',
          description: 'Manage desktop and in-app alerts.',
          options: {
            all: 'Notify me about everything',
            mentions: 'Mentions and direct messages only',
            none: 'Turn off notifications',
          },
        },
        theme: {
          title: 'Theme',
          description: 'Switch between light and dark modes.',
          label: 'Display mode',
          light: 'Light mode',
          dark: 'Dark mode',
        },
        language: {
          title: 'Language',
          description: 'Choose the interface language.',
          label: 'Language',
          korean: '한국어',
          english: 'English',
        },
        translation: {
          title: 'Auto Translation',
          description: 'Automatically translate messages to your language.',
          label: 'Enable auto translation',
          enabled: 'Auto translation enabled',
          disabled: 'Auto translation disabled',
        },
      },
      devices: {
        title: 'Signed-in devices',
        description: 'Review where you are currently signed in and sign out remotely.',
        table: {
          device: 'Device',
          location: 'Location',
          loggedInAt: 'Logged in',
          lastActive: 'Last active',
          action: 'Action',
        },
        revoke: 'Sign out on this device',
        empty: 'No other active sessions.',
      },
    },
    workspaceAdmin: {
      backToWorkspace: 'Back to workspace',
      navDashboard: 'Overview',
      navMembers: 'Members',
      navInviteManagement: 'Invite management',
      navChannels: 'Channels',
      navGroups: 'Groups',
      navPermissions: 'Permissions',
      navIntegrations: 'Integrations',
      navSecurity: 'Security',
      navAuditLog: 'Audit log',
      navAiAssistant: 'AI assistant',
      navAiSearch: 'AI search',
      dashboardTitle: 'Workspace insights',
      dashboardSubtitle: 'Monitor activity and keep your workspace organised.',
      statMembers: 'Total members',
      statChannels: 'Active channels',
      statMessages: 'Messages today',
      statActiveUsers: 'Active users',
      recentActivity: 'Recent activity',
      workspaceOverviewTitle: 'Workspace profile',
      workspaceOverviewDescription: 'Update the workspace name, description, and visibility.',
      workspaceNameLabel: 'Workspace name',
      workspaceDescriptionLabel: 'Description',
      defaultChannelLabel: 'Default welcome channel',
      autoInviteLabel: 'Auto invite new teammates to default channels',
      twoFactorLabel: 'Require 2FA for admins',
      saveChanges: 'Save changes',
      membersTitle: 'Manage members',
      membersDescription: 'Review roles and invite teammates.',
      membersInviteStatusTitle: 'Invitation status',
      membersInviteStatusDescription: 'Review outstanding workspace invitations and see who has joined.',
      membersInviteStatusEmpty: 'No pending invitations.',
      membersInviteStatusAccepted: 'Accepted',
      membersInviteStatusPending: 'Pending',
      membersInviteStatusExpired: 'Expired',
      membersBlockedTitle: 'Blocked users',
      membersBlockedDescription: 'Suspended or blocked accounts are listed here.',
      membersBlockedEmpty: 'No blocked accounts.',
      membersBlockedUnblock: 'Unblock',
      membersParticipantsTitle: 'Workspace participants',
      membersParticipantsDescription: 'Includes both members and guest accounts.',
      membersExport: 'Export member list',
      membersMoveToGroup: 'Move selected to group',
      membersHistoryTitle: 'Join & leave history',
      membersHistoryDescription: 'Track all workspace membership changes.',
      membersHistoryEmpty: 'No membership changes recorded yet.',
      membersHistoryActionJoin: 'joined the workspace',
      membersHistoryActionLeave: 'left the workspace',
      membersHistoryActionInvited: 'was invited',
      inviteMember: 'Invite member',
      inviteManagementTitle: 'Invite management',
      inviteManagementDescription: 'Track pending invites and manage reusable invite links.',
      inviteManagementPendingTitle: 'Pending invitations',
      inviteManagementLinksTitle: 'Reusable invite links',
      inviteManagementLinksEmpty: 'No active invite links yet.',
      inviteManagementLinkMember: 'Member link',
      inviteManagementLinkGuest: 'Guest link',
      inviteManagementCopy: 'Copy link',
      inviteManagementCopied: 'Copied!',
      inviteManagementLinksDescription: 'Review reusable links shared with teammates or guests.',
      roleOwner: 'Owner',
      roleAdmin: 'Admin',
      roleMember: 'Member',
      permissionsTitle: 'Permission controls',
      permissionsDescription: 'Define who can create channels, invite members, and manage billing.',
      permissionCreateChannels: 'Allow members to create public channels',
      permissionPrivateChannels: 'Allow members to create private channels',
      permissionManageIntegrations: 'Allow admins to manage integrations',
      permissionManageBilling: 'Restrict billing settings to owners only',
      integrationsTitle: 'Connected integrations',
      integrationsDescription: 'Keep tools in sync by managing integrations.',
      integrationsStatusActive: 'Active',
      integrationsStatusPaused: 'Paused',
      integrationsStatusRequest: 'Request access',
      securityTitle: 'Security & compliance',
      securityDescription: 'Enforce workspace policies and retention rules.',
      retentionLabel: 'Message retention (days)',
      auditLogTitle: 'Audit log',
      auditLogDescription: 'Track important actions taken across the workspace.',
      auditViewMore: 'View more logs',
      groupsTitle: 'Group management',
      groupsDescription: 'Create groups and control channel access per group.',
      groupsCreate: 'Create group',
      groupsMembersLabel: 'Members',
      groupsChannelsLabel: 'Channel access',
      groupsAllChannels: 'Workspace channels',
      groupsSave: 'Save changes',
    },
  },
  ko: {
    welcome: '환영합니다',
    startWithSocial: '소셜 계정으로 간편하게 시작하세요',
    github: 'GitHub으로 계속하기',
    google: 'Google로 계속하기',
    terms: '계속 진행하시면 서비스 약관 및 개인정보 처리방침에 동의하는 것으로 간주됩니다.',
    termsOfService: '서비스 약관',
    privacyPolicy: '개인정보 처리방침',
    korean: '한국어',
    english: 'English',
    channels: '채널',
    categories: '카테고리',
    favorites: '즐겨찾기',
    favoritesEmpty: '즐겨찾기한 채널이 없습니다.',
    createCategory: '카테고리 만들기',
    inviteMembers: '멤버 초대하기',
    createNewWorkspace: '새 워크스페이스 생성',
    dashboard: '대시보드',
    search: '검색',
    directMessages: '다이렉트 메시지',
    appConnect: '앱 커넥트',
    online: '온라인',
    offline: '오프라인',
    directory: '디렉토리',
    inbox: '수신함',
    unreadCount: '{{count}}',
    unreadCountMax: '99+',
    statusLabels: {
      online: '온라인',
      offline: '오프라인',
      away: '자리비움',
      busy: '방해 금지',
    },
    copy: {
      copy: '복사',
      copied: '복사됨',
    },
    modals: {
      titles: {
        search: '채널 내 검색',
        members: '멤버 목록',
        pinned: '고정된 메시지',
        threads: '스레드 목록',
        info: '채널 정보',
        notifications: '알림',
        createCategory: '새 카테고리 만들기',
        inviteMember: '멤버 초대하기',
        inviteGuest: '게스트 초대하기',
        inviteResult: '초대 완료 안내',
        fileUpload: '파일 업로드',
        channelFiles: '채널 파일',
        mention: '@ 사용자 언급하기',
        addChannel: '채널 추가',
        addDM: 'DM 추가',
        addApp: '앱 추가',
        addFavorite: '즐겨찾기 관리',
      },
      addChannel: {
        description: '{{category}} 카테고리에 새 채널을 추가합니다.',
        nameLabel: '채널 이름',
        namePlaceholder: '예: design-review',
        descLabel: '설명',
        descPlaceholder: '채널의 목적을 간단히 작성하세요.',
        submit: '채널 만들기',
      },
      addDM: {
        searchLabel: '사용자 검색',
        searchPlaceholder: '이름 또는 이메일로 검색하세요.',
        empty: '추가할 사용자가 없습니다.',
      },
      addApp: {
        description: '워크스페이스에 앱을 연동하세요.',
        addButton: '추가',
        empty: '추가 가능한 앱이 없습니다.',
        itemDescription: '즐겨 사용하는 도구를 연동해보세요.',
      },
      addFavorite: {
        description: '즐겨찾기에 표시할 채널을 선택하세요.',
        add: '즐겨찾기 추가',
        remove: '즐겨찾기 해제',
        empty: '추가할 채널이 없습니다.',
      },
      inviteMember: {
        description: '이메일이나 유효 기간이 있는 초대 링크로 팀원을 초대하세요.',
        tabs: {
          direct: '이메일로 초대',
          link: '초대 링크 생성',
        },
        email: {
          searchLabel: '초대할 멤버 이메일 검색',
          searchPlaceholder: '이름 또는 이메일을 입력하세요',
          emptySelection: '선택된 멤버가 없습니다.',
          groupLabel: '그룹 설정',
          sendButton: '초대 보내기',
          successTitle: '초대 메일을 전송했습니다.',
          successSubtitle: '각 멤버에게 추적 가능한 전용 링크가 발급됩니다.',
          copyLink: '초대 링크 복사',
        },
        link: {
          description: '링크 만료와 사용 제한을 설정하세요.',
          expirationLabel: '만료 시간',
          expirationOptions: {
            '24h': '24시간',
            '7d': '7일',
            '30d': '30일',
            never: '만료 없음',
          },
          usageLabel: '사용 제한',
          usageOptions: {
            '1': '1회',
            '5': '5회',
            '10': '10회',
            '50': '50회',
            unlimited: '무제한',
            single: '1회',
          },
          generateButton: '초대 링크 생성',
          copyButton: '링크 복사',
          successTitle: '초대 링크가 준비되었습니다.',
          successSubtitle: '팀원에게 아래 링크를 공유하세요.',
        },
        history: {
          title: '생성된 초대 링크',
          empty: '아직 생성된 링크가 없습니다.',
          created: '생성',
          expires: '만료',
          usage: '사용 제한',
        },
      },
      inviteGuest: {
        description: '{{channel}} 채널에 게스트를 초대하거나 유효 기간이 있는 링크를 생성하세요.',
        tabs: {
          direct: '이메일로 초대',
          link: '게스트 링크 생성',
        },
        email: {
          searchLabel: '게스트 이메일 검색',
          searchPlaceholder: '게스트 이메일을 입력하세요',
          emptySelection: '선택된 게스트가 없습니다.',
          sendButton: '초대 보내기',
          successTitle: '게스트 초대를 전송했습니다.',
          successSubtitle: '전용 링크를 통해 게스트가 채널에 참여할 수 있습니다.',
          copyLink: '게스트 링크 복사',
        },
        link: {
          description: '만료와 사용 제한을 설정한 뒤 링크를 공유하세요.',
          expirationLabel: '만료 시간',
          expirationOptions: {
            '24h': '24시간',
            '7d': '7일',
            '30d': '30일',
            never: '만료 없음',
          },
          usageLabel: '사용 제한',
          usageOptions: {
            '1': '1회',
            '5': '5회',
            '10': '10회',
            '50': '50회',
            unlimited: '무제한',
            single: '1회',
          },
          generateButton: '게스트 링크 생성',
          copyButton: '링크 복사',
          successTitle: '게스트 링크가 준비되었습니다.',
          successSubtitle: '외부 협업자와 링크를 공유하세요.',
        },
        history: {
          title: '게스트 링크 기록',
          empty: '아직 생성된 게스트 링크가 없습니다.',
          created: '생성',
          expires: '만료',
          usage: '사용 제한',
        },
        context: {
          channelPrefix: '채널',
        },
      },
      members: {
        inviteGuestButton: '게스트 초대',
      },
      inviteResult: {
        title: '초대 완료 안내',
        memberDescription: '다음 팀원에게 고유한 초대 링크가 포함된 이메일을 보냈습니다.',
        guestDescription: '다음 게스트에게 고유한 초대 링크가 포함된 이메일을 보냈습니다.',
        linkDescription: '필요한 사람에게 이 링크를 공유하세요.',
        close: '닫기',
        codeLabel: '코드',
        createdLabel: '생성일',
      },
      inbox: {
        title: '수신함',
        empty: '알림이 없습니다.',
        tabs: {
          all: '전체',
          important: '중요한 메시지',
          byWorkspace: '워크스페이스별',
        },
        actions: {
          markAsRead: '읽음 처리',
          delete: '삭제',
          markAllRead: '모두 읽음 처리',
        },
        filters: {
          unreadOnly: '읽지 않은 항목만',
          showAll: '전체 표시',
        },
      },
      workspaceProfile: {
        title: '워크스페이스 프로필',
        description: '이 워크스페이스에서 사용할 프로필을 설정하세요.',
        displayName: '표시 이름',
        statusMessage: '상태 메시지',
        avatar: '아바타',
        saveButton: '변경사항 저장',
      },
      deactivateAccount: {
        title: '계정 비활성화',
        description: '정말 계정을 비활성화하시겠습니까? 데이터는 보존되지만 접근할 수 없습니다.',
        confirmButton: '비활성화',
        cancelButton: '취소',
        warning: '이 작업은 고객 지원팀에 문의하여 되돌릴 수 있습니다.',
      },
      deleteAccount: {
        title: '계정 삭제',
        description: '정말 계정을 영구적으로 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
        confirmButton: '영구 삭제',
        cancelButton: '취소',
        warning: '모든 데이터, 메시지, 워크스페이스가 영구적으로 삭제됩니다.',
        typeToConfirm: '확인을 위해 "삭제"를 입력하세요',
        confirmPlaceholder: '삭제',
      },
    },
    message: {
      actions: {
        copy: '복사',
        react: '반응 추가',
        reply: '답글',
        translate: '번역하기',
        forward: '전달하기',
        pin: '고정하기',
        unpin: '고정 해제',
        startThread: '스레드 시작',
        edit: '수정하기',
        delete: '삭제하기',
        more: '더보기',
      },
      translated: '{{lang}}에서 번역됨',
      translating: '번역 중...',
      translationNotice: '이 문장은 번역되었습니다.',
      showOriginal: '원문보기',
      hideOriginal: '원문 숨기기',
      forwardTo: '전달할 위치',
      forwardSuccess: '메시지가 전달되었습니다',
    },
    workspace: {
      settings: '워크스페이스 설정',
      create: '워크스페이스 생성',
      joinWithLink: '초대 링크로 참여',
      inviteCodePlaceholder: '초대 코드를 입력하세요',
      joinButton: '워크스페이스 참여',
    },
    directory: {
      title: '디렉토리',
      searchPlaceholder: '멤버 이름 또는 이메일을 검색하세요...',
      sortLabel: '정렬',
      sortOptions: {
        nameAsc: '이름(ㄱ-ㅎ)',
        joinDesc: '가입일 최신순',
        roleAsc: '역할',
        status: '온라인 상태',
      },
      pageSizeLabel: '페이지당 인원',
      pagination: {
        previous: '이전',
        next: '다음',
        summary: '총 {{total}}명 중 {{from}}-{{to}}명 표시',
      },
      columns: {
        name: '멤버',
        email: '이메일',
        provider: '프로바이더',
        joinedAt: '가입일',
        group: '그룹',
        role: '역할',
        status: '상태',
      },
      empty: '멤버를 찾을 수 없습니다.',
    },
    userSettings: {
      title: '사용자 설정',
      navProfile: '프로필',
      navPreferences: '환경 설정',
      navLogout: '로그아웃',
      navDevices: '로그인된 기기',
      profile: {
        title: '내 프로필',
        description: '아바타와 기본 정보를 수정합니다.',
        deactivateTitle: '계정 비활성화',
        deactivateDescription: '데이터를 유지한 채 일시적으로 계정을 잠급니다.',
        deactivateButton: '계정 비활성화',
        deleteTitle: '계정 삭제',
        deleteDescription: '계정과 관련 데이터를 영구적으로 삭제합니다.',
        deleteButton: '계정 삭제',
        nameLabel: '실제 이름',
        emailLabel: '이메일',
        socialLoginLabel: '소셜 로그인',
        socialLoginSuffix: '계정으로 가입함',
        avatarChange: '변경',
        saveButton: '변경사항 저장',
      },
      account: {
        title: '소속 워크스페이스',
        description: '현재 참여 중인 워크스페이스와 역할입니다.',
        workspaceColumn: '워크스페이스',
        roleColumn: '역할',
        joinedColumn: '가입일',
        empty: '소속된 워크스페이스가 없습니다.',
      },
      logout: {
        title: '로그아웃',
        description: '현재 기기에서 세션을 종료합니다.',
        button: '로그아웃',
        modalTitle: '로그아웃 하시겠어요?',
        modalDescription: '언제든 다시 로그인할 수 있습니다. 저장되지 않은 변경사항은 사라질 수 있습니다.',
        confirm: '로그아웃',
        cancel: '취소',
        inProgress: '로그아웃 중...',
      },
      preferences: {
        notifications: {
          title: '알림 설정',
          description: '데스크톱 및 앱 알림을 관리하세요.',
          options: {
            all: '모든 활동에 대해 알림',
            mentions: '멘션 및 다이렉트 메시지만',
            none: '알림 끄기',
          },
        },
        theme: {
          title: '테마 설정',
          description: '라이트/다크 모드를 전환할 수 있습니다.',
          label: '표시 모드',
          light: '라이트 모드',
          dark: '다크 모드',
        },
        language: {
          title: '언어 설정',
          description: '인터페이스 언어를 변경합니다.',
          label: '언어',
          korean: '한국어',
          english: 'English',
        },
        translation: {
          title: '자동 번역',
          description: '메시지를 자동으로 내 언어로 번역합니다.',
          label: '자동 번역 활성화',
          enabled: '자동 번역 켜짐',
          disabled: '자동 번역 꺼짐',
        },
      },
      devices: {
        title: '로그인된 기기',
        description: '현재 로그인 중인 기기를 확인하고 원격으로 로그아웃할 수 있습니다.',
        table: {
          device: '기기',
          location: '위치',
          loggedInAt: '로그인 시각',
          lastActive: '마지막 활동',
          action: '조치',
        },
        revoke: '이 기기에서 로그아웃',
        empty: '다른 기기에서 로그인된 세션이 없습니다.',
      },
    },
    workspaceAdmin: {
      backToWorkspace: '워크스페이스로 돌아가기',
      navDashboard: '개요 대시보드',
      navMembers: '멤버 관리',
      navInviteManagement: '초대 관리',
      navChannels: '채널 관리',
      navGroups: '그룹 관리',
      navPermissions: '권한 설정',
      navIntegrations: '연동 관리',
      navSecurity: '보안 설정',
      navAuditLog: '감사 로그',
      dashboardTitle: '워크스페이스 인사이트',
      dashboardSubtitle: '팀 활동을 모니터링하고 워크스페이스를 정돈하세요.',
      navAiAssistant: 'AI 어시스턴트',
      navAiSearch: 'AI 검색',
      statMembers: '멤버',
      statChannels: '활성 채널',
      statMessages: '오늘 메시지',
      statActiveUsers: '활성 사용자',
      recentActivity: '최근 활동',
      workspaceOverviewTitle: '워크스페이스 정보',
      workspaceOverviewDescription: '워크스페이스 이름, 설명, 기본 설정을 관리합니다.',
      workspaceNameLabel: '워크스페이스 이름',
      workspaceDescriptionLabel: '설명',
      defaultChannelLabel: '기본 환영 채널',
      autoInviteLabel: '새 멤버를 기본 채널에 자동 초대',
      twoFactorLabel: '관리자에게 2단계 인증 요구',
      saveChanges: '변경사항 저장',
      membersTitle: '멤버 관리',
      membersDescription: '역할을 검토하고 팀원을 초대하세요.',
      membersInviteStatusTitle: '초대 상태',
      membersInviteStatusDescription: '발송된 초대와 가입 여부를 확인하세요.',
      membersInviteStatusEmpty: '대기 중인 초대가 없습니다.',
      membersInviteStatusAccepted: '승인됨',
      membersInviteStatusPending: '대기 중',
      membersInviteStatusExpired: '만료됨',
      membersBlockedTitle: '차단된 사용자',
      membersBlockedDescription: '차단되었거나 정지된 계정을 확인할 수 있습니다.',
      membersBlockedEmpty: '차단된 사용자가 없습니다.',
      membersBlockedUnblock: '차단 해제',
      membersParticipantsTitle: '워크스페이스 참여자',
      membersParticipantsDescription: '멤버와 게스트 계정을 모두 포함합니다.',
      membersExport: '멤버 목록 내보내기',
      membersMoveToGroup: '선택한 멤버 그룹 이동',
      membersHistoryTitle: '입장 및 탈퇴 내역',
      membersHistoryDescription: '워크스페이스 멤버십 변동을 모두 확인할 수 있습니다.',
      membersHistoryEmpty: '멤버십 변동 기록이 없습니다.',
      membersHistoryActionJoin: '워크스페이스에 참여했습니다.',
      membersHistoryActionLeave: '워크스페이스를 떠났습니다.',
      membersHistoryActionInvited: '워크스페이스 초대를 받았습니다.',
      inviteMember: '멤버 초대',
      inviteManagementTitle: '초대 관리',
      inviteManagementDescription: '초대 현황을 확인하고 재사용 가능한 초대 링크를 관리하세요.',
      inviteManagementPendingTitle: '대기 중인 초대',
      inviteManagementLinksTitle: '재사용 가능한 초대 링크',
      inviteManagementLinksEmpty: '활성화된 초대 링크가 아직 없습니다.',
      inviteManagementLinkMember: '멤버 초대 링크',
      inviteManagementLinkGuest: '게스트 초대 링크',
      inviteManagementCopy: '링크 복사',
      inviteManagementCopied: '복사됨',
      inviteManagementLinksDescription: '멤버 또는 게스트와 공유 중인 재사용 링크를 확인하세요.',
      roleOwner: '소유자',
      roleAdmin: '관리자',
      roleMember: '멤버',
      permissionsTitle: '권한 제어',
      permissionsDescription: '채널 생성, 초대, 결제 관리를 누가 할 수 있는지 정의합니다.',
      permissionCreateChannels: '멤버가 공개 채널을 생성할 수 있음',
      permissionPrivateChannels: '멤버가 비공개 채널을 생성할 수 있음',
      permissionManageIntegrations: '관리자가 연동을 관리할 수 있음',
      permissionManageBilling: '결제 설정은 소유자만 가능',
      integrationsTitle: '연동 관리',
      integrationsDescription: '외부 도구와의 연동 상태를 확인하고 관리합니다.',
      integrationsStatusActive: '사용 중',
      integrationsStatusPaused: '일시 중지',
      integrationsStatusRequest: '권한 요청',
      securityTitle: '보안 및 컴플라이언스',
      securityDescription: '워크스페이스 정책과 보존 규칙을 적용합니다.',
      retentionLabel: '메시지 보존 기간 (일)',
      auditLogTitle: '감사 로그',
      auditLogDescription: '워크스페이스에서 발생한 주요 작업을 추적합니다.',
      auditViewMore: '로그 더보기',
      groupsTitle: '그룹 관리',
      groupsDescription: '그룹을 생성하고 채널 접근 권한을 설정하세요.',
      groupsCreate: '그룹 생성',
      groupsMembersLabel: '멤버 수',
      groupsChannelsLabel: '채널 접근 권한',
      groupsAllChannels: '워크스페이스 채널',
      groupsSave: '변경사항 저장',
    },
  },
};
