export const strings = {
  en: {
    welcome: 'Welcome',
    startWithSocial: 'Get started easily with your social account',
    github: 'Continue with GitHub',
    gitlab: 'Continue with GitLab',
    google: 'Continue with Google',
    terms: 'By continuing, you agree to our Terms of Service and Privacy Policy.',
    korean: '한국어',
    english: 'English',
    channels: 'Channels',
    categories: 'Categories',
    favorites: 'Favorites',
    favoritesEmpty: 'No favourite channels yet.',
    createCategory: 'Create Category',
    inviteMembers: 'Invite Members',
    createNewWorkspace: 'Create New Workspace',
    dashboard: 'Dashboard',
    search: 'Search',
    directMessages: 'Direct Messages',
    appConnect: 'App Connect',
    online: 'Online',
    offline: 'Offline',
    statusLabels: {
      online: 'Online',
      offline: 'Offline',
      away: 'Away',
      busy: 'Do not disturb',
    },
    modals: {
      titles: {
        search: 'Search in Channel',
        members: 'Members',
        pinned: 'Pinned Messages',
        threads: 'Threads',
        info: 'Channel Info',
        notifications: 'Notifications',
        createCategory: 'Create Category',
        invite: 'Invite Members',
        fileUpload: 'Upload Files',
        channelFiles: 'Channel Files',
        mention: 'Mention',
        addChannel: 'Add Channel',
        addDM: 'Start a DM',
        addApp: 'Add App',
        addFavorite: 'Manage Favorites',
      },
      addChannel: {
        description: 'Add a new channel to {{category}}.',
        nameLabel: 'Channel name',
        namePlaceholder: 'e.g. design-review',
        descLabel: 'Description',
        descPlaceholder: 'Briefly describe the purpose of this channel.',
        submit: 'Create channel',
      },
      addDM: {
        searchLabel: 'Search members',
        searchPlaceholder: 'Find by name or email',
        empty: 'No additional members available.',
      },
      addApp: {
        description: 'Connect apps to your workspace.',
        addButton: 'Add',
        empty: 'No apps available.',
        itemDescription: 'Keep your favourite tools in sync.',
      },
      addFavorite: {
        description: 'Choose which channels should appear in your favourites.',
        add: 'Add to favourites',
        remove: 'Remove from favourites',
        empty: 'No channels available.',
      },
    },
    directory: {
      title: 'Directory',
      searchPlaceholder: 'Search members...',
      sortLabel: 'Sort',
      sortOptions: {
        nameAsc: 'Name A-Z',
        joinDesc: 'Newest members',
        roleAsc: 'Role',
        status: 'Status',
      },
      pageSizeLabel: 'Rows per page',
      pagination: {
        previous: 'Previous',
        next: 'Next',
        summary: 'Showing {{from}}-{{to}} of {{total}} members',
      },
      columns: {
        name: 'Member',
        email: 'Email',
        provider: 'Provider',
        joinedAt: 'Joined',
        group: 'Group',
        role: 'Role',
        status: 'Status',
      },
      empty: 'No members found.',
    },
    workspaceAdmin: {
      backToWorkspace: 'Back to workspace',
      navDashboard: 'Overview',
      navMembers: 'Members',
      navChannels: 'Channels',
      navPermissions: 'Permissions',
      navIntegrations: 'Integrations',
      navSecurity: 'Security',
      navAuditLog: 'Audit log',
      dashboardTitle: 'Workspace insights',
      dashboardSubtitle: 'Monitor activity and keep your workspace organised.',
      statMembers: 'Total members',
      statChannels: 'Active channels',
      statMessages: 'Messages today',
      statActiveUsers: 'Active users',
      recentActivity: 'Recent activity',
      workspaceOverviewTitle: 'Workspace profile',
      workspaceOverviewDescription: 'Update the workspace name, description, and visibility.',
      workspaceNameLabel: 'Workspace name',
      workspaceDescriptionLabel: 'Description',
      defaultChannelLabel: 'Default welcome channel',
      autoInviteLabel: 'Auto invite new teammates to default channels',
      twoFactorLabel: 'Require 2FA for admins',
      saveChanges: 'Save changes',
      membersTitle: 'Manage members',
      membersDescription: 'Review roles and invite teammates.',
      inviteMember: 'Invite member',
      roleOwner: 'Owner',
      roleAdmin: 'Admin',
      roleMember: 'Member',
      permissionsTitle: 'Permission controls',
      permissionsDescription: 'Define who can create channels, invite members, and manage billing.',
      permissionCreateChannels: 'Allow members to create public channels',
      permissionPrivateChannels: 'Allow members to create private channels',
      permissionManageIntegrations: 'Allow admins to manage integrations',
      permissionManageBilling: 'Restrict billing settings to owners only',
      integrationsTitle: 'Connected integrations',
      integrationsDescription: 'Keep tools in sync by managing integrations.',
      integrationsStatusActive: 'Active',
      integrationsStatusPaused: 'Paused',
      integrationsStatusRequest: 'Request access',
      securityTitle: 'Security & compliance',
      securityDescription: 'Enforce workspace policies and retention rules.',
      retentionLabel: 'Message retention (days)',
      auditLogTitle: 'Audit log',
      auditLogDescription: 'Track important actions taken across the workspace.',
      auditViewMore: 'View more logs',
    },
  },
  ko: {
    welcome: '환영합니다',
    startWithSocial: '소셜 계정으로 간편하게 시작하세요',
    github: 'GitHub으로 계속하기',
    gitlab: 'GitLab으로 계속하기',
    google: 'Google로 계속하기',
    terms: '계속 진행하시면 서비스 약관 및 개인정보 처리방침에 동의하는 것으로 간주됩니다.',
    korean: '한국어',
    english: 'English',
    channels: '채널',
    categories: '카테고리',
    favorites: '즐겨찾기',
    favoritesEmpty: '즐겨찾기한 채널이 없습니다.',
    createCategory: '카테고리 만들기',
    inviteMembers: '멤버 초대하기',
    createNewWorkspace: '새 워크스페이스 생성',
    dashboard: '대시보드',
    search: '검색',
    directMessages: '다이렉트 메시지',
    appConnect: '앱 커넥트',
    online: '온라인',
    offline: '오프라인',
    statusLabels: {
      online: '온라인',
      offline: '오프라인',
      away: '자리비움',
      busy: '방해 금지',
    },
    modals: {
      titles: {
        search: '채널 내 검색',
        members: '멤버 목록',
        pinned: '고정된 메시지',
        threads: '스레드 목록',
        info: '채널 정보',
        notifications: '알림',
        createCategory: '새 카테고리 만들기',
        invite: '멤버 초대하기',
        fileUpload: '파일 업로드',
        channelFiles: '채널 파일',
        mention: '@ 사용자 언급하기',
        addChannel: '채널 추가',
        addDM: 'DM 추가',
        addApp: '앱 추가',
        addFavorite: '즐겨찾기 관리',
      },
      addChannel: {
        description: '{{category}} 카테고리에 새 채널을 추가합니다.',
        nameLabel: '채널 이름',
        namePlaceholder: '예: design-review',
        descLabel: '설명',
        descPlaceholder: '채널의 목적을 간단히 작성하세요.',
        submit: '채널 만들기',
      },
      addDM: {
        searchLabel: '사용자 검색',
        searchPlaceholder: '이름 또는 이메일로 검색하세요.',
        empty: '추가할 사용자가 없습니다.',
      },
      addApp: {
        description: '워크스페이스에 앱을 연동하세요.',
        addButton: '추가',
        empty: '추가 가능한 앱이 없습니다.',
        itemDescription: '즐겨 사용하는 도구를 연동해보세요.',
      },
      addFavorite: {
        description: '즐겨찾기에 표시할 채널을 선택하세요.',
        add: '즐겨찾기 추가',
        remove: '즐겨찾기 해제',
        empty: '추가할 채널이 없습니다.',
      },
    },
    directory: {
      title: '디렉토리',
      searchPlaceholder: '멤버 이름 또는 이메일을 검색하세요...',
      sortLabel: '정렬',
      sortOptions: {
        nameAsc: '이름(ㄱ-ㅎ)',
        joinDesc: '가입일 최신순',
        roleAsc: '역할',
        status: '온라인 상태',
      },
      pageSizeLabel: '페이지당 인원',
      pagination: {
        previous: '이전',
        next: '다음',
        summary: '총 {{total}}명 중 {{from}}-{{to}}명 표시',
      },
      columns: {
        name: '멤버',
        email: '이메일',
        provider: '프로바이더',
        joinedAt: '가입일',
        group: '그룹',
        role: '역할',
        status: '상태',
      },
      empty: '멤버를 찾을 수 없습니다.',
    },
    workspaceAdmin: {
      backToWorkspace: '워크스페이스로 돌아가기',
      navDashboard: '개요 대시보드',
      navMembers: '멤버 관리',
      navChannels: '채널 관리',
      navPermissions: '권한 설정',
      navIntegrations: '연동 관리',
      navSecurity: '보안 설정',
      navAuditLog: '감사 로그',
      dashboardTitle: '워크스페이스 인사이트',
      dashboardSubtitle: '팀 활동을 모니터링하고 워크스페이스를 정돈하세요.',
    navAiAssistant: 'AI 어시스턴트',
    navAiSearch: 'AI 검색',
    statMembers: '멤버',
      statChannels: '활성 채널',
      statMessages: '오늘 메시지',
      statActiveUsers: '활성 사용자',
      recentActivity: '최근 활동',
      workspaceOverviewTitle: '워크스페이스 정보',
      workspaceOverviewDescription: '워크스페이스 이름, 설명, 기본 설정을 관리합니다.',
      workspaceNameLabel: '워크스페이스 이름',
      workspaceDescriptionLabel: '설명',
      defaultChannelLabel: '기본 환영 채널',
      autoInviteLabel: '새 멤버를 기본 채널에 자동 초대',
      twoFactorLabel: '관리자에게 2단계 인증 요구',
      saveChanges: '변경사항 저장',
      membersTitle: '멤버 관리',
      membersDescription: '역할을 검토하고 팀원을 초대하세요.',
      inviteMember: '멤버 초대',
      roleOwner: '소유자',
      roleAdmin: '관리자',
      roleMember: '멤버',
      permissionsTitle: '권한 제어',
      permissionsDescription: '채널 생성, 초대, 결제 관리를 누가 할 수 있는지 정의합니다.',
      permissionCreateChannels: '멤버가 공개 채널을 생성할 수 있음',
      permissionPrivateChannels: '멤버가 비공개 채널을 생성할 수 있음',
      permissionManageIntegrations: '관리자가 연동을 관리할 수 있음',
      permissionManageBilling: '결제 설정은 소유자만 가능',
      integrationsTitle: '연동 관리',
      integrationsDescription: '외부 도구와의 연동 상태를 확인하고 관리합니다.',
      integrationsStatusActive: '사용 중',
      integrationsStatusPaused: '일시 중지',
      integrationsStatusRequest: '권한 요청',
      securityTitle: '보안 및 컴플라이언스',
      securityDescription: '워크스페이스 정책과 보존 규칙을 적용합니다.',
      retentionLabel: '메시지 보존 기간 (일)',
      auditLogTitle: '감사 로그',
      auditLogDescription: '워크스페이스에서 발생한 주요 작업을 추적합니다.',
      auditViewMore: '로그 더보기',
    },
  },
};
