export const strings = {
  en: {
    welcome: 'Welcome',
    startWithSocial: 'Get started easily with your social account',
    github: 'Continue with GitHub',
    gitlab: 'Continue with GitLab',
    google: 'Continue with Google',
    terms: 'By continuing, you agree to our Terms of Service and Privacy Policy.',
    korean: '한국어',
    english: 'English',
    channels: 'Channels',
    createCategory: 'Create Category',
    inviteMembers: 'Invite Members',
    createNewWorkspace: 'Create New Workspace',
    dashboard: 'Dashboard',
    search: 'Search',
    directory: 'Directory',
    directMessages: 'Direct Messages',
    online: 'Online',
  },
  ko: {
    welcome: '환영합니다',
    startWithSocial: '소셜 계정으로 간편하게 시작하세요',
    github: 'GitHub으로 계속하기',
    gitlab: 'GitLab으로 계속하기',
    google: 'Google로 계속하기',
    terms: '계속 진행하시면 서비스 약관 및 개인정보 처리방침에 동의하는 것으로 간주됩니다.',
    korean: '한국어',
    english: 'English',
    channels: '채널',
    createCategory: '카테고리 만들기',
    inviteMembers: '멤버 초대하기',
    createNewWorkspace: '새 워크스페이스 생성',
    dashboard: '대시보드',
    search: '검색',
    directory: '디렉토리',
    directMessages: '다이렉트 메시지',
    online: '온라인',
  },
};
