export const modalsStrings = {
  en: {
    modals: {
      titles: {
        search: 'Search in Channel',
        members: 'Members',
        pinned: 'Pinned Messages',
        threads: 'Threads',
        info: 'Channel Info',
        notifications: 'Notifications',
        createCategory: 'Create Category',
        inviteMember: 'Invite member',
        inviteGuest: 'Invite guest',
        inviteResult: 'Invitation summary',
        fileUpload: 'Upload Files',
        channelFiles: 'Channel Files',
        mention: 'Mention',
        addChannel: 'Add Channel',
        addDM: 'Start a DM',
        addApp: 'Add App',
        addFavorite: 'Manage Favorites',
      },
      addChannel: {
        description: 'Add a new channel to {{category}}.',
        nameLabel: 'Channel name',
        namePlaceholder: 'e.g. design-review',
        descLabel: 'Description',
        descPlaceholder: 'Briefly describe the purpose of this channel.',
        submit: 'Create channel',
      },
      addDM: {
        searchLabel: 'Search members',
        searchPlaceholder: 'Find by name or email',
        empty: 'No additional members available.',
      },
      addApp: {
        description: 'Connect apps to your workspace.',
        addButton: 'Add',
        empty: 'No apps available.',
        itemDescription: 'Keep your favourite tools in sync.',
      },
      addFavorite: {
        description: 'Choose which channels should appear in your favourites.',
        add: 'Add to favourites',
        remove: 'Remove from favourites',
        empty: 'No channels available.',
      },
      inviteMember: {
        description: 'Invite teammates by email or share a time-bound invite link.',
        tabs: {
          direct: 'Invite by email',
          link: 'Generate invite link',
        },
        email: {
          searchLabel: 'Search teammate email',
          searchPlaceholder: 'Enter a name or email address',
          emptySelection: 'No recipients selected.',
          groupLabel: 'Assign to groups',
          sendButton: 'Send invites',
          successTitle: 'Invitations sent',
          successSubtitle: 'Each teammate receives a personalised, traceable link.',
          copyLink: 'Copy invite link',
        },
        link: {
          description: 'Configure expiration and usage limits before sharing.',
          expirationLabel: 'Expiration',
          expirationOptions: {
            '24h': '24 hours',
            '7d': '7 days',
            '30d': '30 days',
            never: 'No expiration',
          },
          usageLabel: 'Usage limit',
          usageOptions: {
            '1': '1 use',
            '5': '5 uses',
            '10': '10 uses',
            '50': '50 uses',
            unlimited: 'Unlimited',
            single: '1 use',
          },
          generateButton: 'Generate invite link',
          copyButton: 'Copy link',
          successTitle: 'Invite link ready',
          successSubtitle: 'Share this link with your team.',
        },
        history: {
          title: 'Invite link history',
          empty: 'No invite links generated yet.',
          created: 'Created',
          expires: 'Expires',
          usage: 'Usage limit',
        },
      },
      inviteGuest: {
        description: 'Invite guests to {{channel}} or generate a time-bound guest link.',
        tabs: {
          direct: 'Invite by email',
          link: 'Generate guest link',
        },
        email: {
          searchLabel: 'Search guest email',
          searchPlaceholder: 'Enter a guest email address',
          emptySelection: 'No guests selected.',
          sendButton: 'Send guest invites',
          successTitle: 'Guest invitations sent',
          successSubtitle: 'Guests can join via the personalised link below.',
          copyLink: 'Copy guest link',
        },
        link: {
          description: 'Configure expiration and usage limits before sharing.',
          expirationLabel: 'Expiration',
          expirationOptions: {
            '24h': '24 hours',
            '7d': '7 days',
            '30d': '30 days',
            never: 'No expiration',
          },
          usageLabel: 'Usage limit',
          usageOptions: {
            '1': '1 use',
            '5': '5 uses',
            '10': '10 uses',
            '50': '50 uses',
            unlimited: 'Unlimited',
            single: '1 use',
          },
          generateButton: 'Generate guest link',
          copyButton: 'Copy link',
          successTitle: 'Guest link ready',
          successSubtitle: 'Share this link with external collaborators.',
        },
        history: {
          title: 'Guest link history',
          empty: 'No guest links generated yet.',
          created: 'Created',
          expires: 'Expires',
          usage: 'Usage limit',
        },
        context: {
          channelPrefix: 'Channel',
        },
      },
      members: {
        inviteGuestButton: 'Invite guest to channel',
      },
      inviteResult: {
        title: 'Invitation summary',
        memberDescription: 'The following teammates received invite emails with unique links.',
        guestDescription: 'The following guests received invite emails with unique links.',
        linkDescription: 'Share this link with anyone who should join.',
        close: 'Close',
        codeLabel: 'Code',
        createdLabel: 'Created',
      },
      inbox: {
        title: 'Inbox',
        empty: 'No notifications yet.',
        tabs: {
          all: 'All',
          important: 'Important',
          byWorkspace: 'By Workspace',
        },
        actions: {
          markAsRead: 'Mark as read',
          delete: 'Delete',
          markAllRead: 'Mark all as read',
        },
        filters: {
          unreadOnly: 'Unread only',
          showAll: 'Show all',
        },
      },
      workspaceProfile: {
        title: 'Workspace Profile',
        description: 'Set your profile for this workspace.',
        displayName: 'Display name',
        statusMessage: 'Status message',
        avatar: 'Avatar',
        saveButton: 'Save changes',
      },
      deactivateAccount: {
        title: 'Deactivate Account',
        description:
          'Are you sure you want to deactivate your account? Your data will be preserved but you won\'t be able to access it.',
        confirmButton: 'Deactivate',
        cancelButton: 'Cancel',
        warning: 'This action can be reversed by contacting support.',
      },
      deleteAccount: {
        title: 'Delete Account',
        description: 'Are you sure you want to permanently delete your account? This action cannot be undone.',
        confirmButton: 'Delete permanently',
        cancelButton: 'Cancel',
        warning: 'All your data, messages, and workspaces will be permanently removed.',
        typeToConfirm: 'Type "DELETE" to confirm',
        confirmPlaceholder: 'DELETE',
      },
    },
  },
  ko: {
    modals: {
      titles: {
        search: '채널 내 검색',
        members: '멤버 목록',
        pinned: '고정된 메시지',
        threads: '스레드 목록',
        info: '채널 정보',
        notifications: '알림',
        createCategory: '새 카테고리 만들기',
        inviteMember: '멤버 초대하기',
        inviteGuest: '게스트 초대하기',
        inviteResult: '초대 완료 안내',
        fileUpload: '파일 업로드',
        channelFiles: '채널 파일',
        mention: '@ 사용자 언급하기',
        addChannel: '채널 추가',
        addDM: 'DM 추가',
        addApp: '앱 추가',
        addFavorite: '즐겨찾기 관리',
      },
      addChannel: {
        description: '{{category}} 카테고리에 새 채널을 추가합니다.',
        nameLabel: '채널 이름',
        namePlaceholder: '예: design-review',
        descLabel: '설명',
        descPlaceholder: '채널의 목적을 간단히 작성하세요.',
        submit: '채널 만들기',
      },
      addDM: {
        searchLabel: '사용자 검색',
        searchPlaceholder: '이름 또는 이메일로 검색하세요.',
        empty: '추가할 사용자가 없습니다.',
      },
      addApp: {
        description: '워크스페이스에 앱을 연동하세요.',
        addButton: '추가',
        empty: '추가 가능한 앱이 없습니다.',
        itemDescription: '즐겨 사용하는 도구를 연동해보세요.',
      },
      addFavorite: {
        description: '즐겨찾기에 표시할 채널을 선택하세요.',
        add: '즐겨찾기 추가',
        remove: '즐겨찾기 해제',
        empty: '추가할 채널이 없습니다.',
      },
      inviteMember: {
        description: '이메일이나 유효 기간이 있는 초대 링크로 팀원을 초대하세요.',
        tabs: {
          direct: '이메일로 초대',
          link: '초대 링크 생성',
        },
        email: {
          searchLabel: '초대할 멤버 이메일 검색',
          searchPlaceholder: '이름 또는 이메일을 입력하세요',
          emptySelection: '선택된 멤버가 없습니다.',
          groupLabel: '그룹 설정',
          sendButton: '초대 보내기',
          successTitle: '초대 메일을 전송했습니다.',
          successSubtitle: '각 멤버에게 추적 가능한 전용 링크가 발급됩니다.',
          copyLink: '초대 링크 복사',
        },
        link: {
          description: '링크 만료와 사용 제한을 설정하세요.',
          expirationLabel: '만료 시간',
          expirationOptions: {
            '24h': '24시간',
            '7d': '7일',
            '30d': '30일',
            never: '만료 없음',
          },
          usageLabel: '사용 제한',
          usageOptions: {
            '1': '1회',
            '5': '5회',
            '10': '10회',
            '50': '50회',
            unlimited: '무제한',
            single: '1회',
          },
          generateButton: '초대 링크 생성',
          copyButton: '링크 복사',
          successTitle: '초대 링크가 준비되었습니다.',
          successSubtitle: '팀원에게 아래 링크를 공유하세요.',
        },
        history: {
          title: '생성된 초대 링크',
          empty: '아직 생성된 링크가 없습니다.',
          created: '생성',
          expires: '만료',
          usage: '사용 제한',
        },
      },
      inviteGuest: {
        description: '{{channel}} 채널에 게스트를 초대하거나 유효 기간이 있는 링크를 생성하세요.',
        tabs: {
          direct: '이메일로 초대',
          link: '게스트 링크 생성',
        },
        email: {
          searchLabel: '게스트 이메일 검색',
          searchPlaceholder: '게스트 이메일을 입력하세요',
          emptySelection: '선택된 게스트가 없습니다.',
          sendButton: '초대 보내기',
          successTitle: '게스트 초대를 전송했습니다.',
          successSubtitle: '전용 링크를 통해 게스트가 채널에 참여할 수 있습니다.',
          copyLink: '게스트 링크 복사',
        },
        link: {
          description: '만료와 사용 제한을 설정한 뒤 링크를 공유하세요.',
          expirationLabel: '만료 시간',
          expirationOptions: {
            '24h': '24시간',
            '7d': '7일',
            '30d': '30일',
            never: '만료 없음',
          },
          usageLabel: '사용 제한',
          usageOptions: {
            '1': '1회',
            '5': '5회',
            '10': '10회',
            '50': '50회',
            unlimited: '무제한',
            single: '1회',
          },
          generateButton: '게스트 링크 생성',
          copyButton: '링크 복사',
          successTitle: '게스트 링크가 준비되었습니다.',
          successSubtitle: '외부 협업자와 링크를 공유하세요.',
        },
        history: {
          title: '게스트 링크 기록',
          empty: '아직 생성된 게스트 링크가 없습니다.',
          created: '생성',
          expires: '만료',
          usage: '사용 제한',
        },
        context: {
          channelPrefix: '채널',
        },
      },
      members: {
        inviteGuestButton: '게스트 초대',
      },
      inviteResult: {
        title: '초대 완료 안내',
        memberDescription: '다음 팀원에게 고유한 초대 링크가 포함된 이메일을 보냈습니다.',
        guestDescription: '다음 게스트에게 고유한 초대 링크가 포함된 이메일을 보냈습니다.',
        linkDescription: '필요한 사람에게 이 링크를 공유하세요.',
        close: '닫기',
        codeLabel: '코드',
        createdLabel: '생성일',
      },
      inbox: {
        title: '수신함',
        empty: '알림이 없습니다.',
        tabs: {
          all: '전체',
          important: '중요한 메시지',
          byWorkspace: '워크스페이스별',
        },
        actions: {
          markAsRead: '읽음 처리',
          delete: '삭제',
          markAllRead: '모두 읽음 처리',
        },
        filters: {
          unreadOnly: '읽지 않은 항목만',
          showAll: '전체 표시',
        },
      },
      workspaceProfile: {
        title: '워크스페이스 프로필',
        description: '이 워크스페이스에서 사용할 프로필을 설정하세요.',
        displayName: '표시 이름',
        statusMessage: '상태 메시지',
        avatar: '아바타',
        saveButton: '변경사항 저장',
      },
      deactivateAccount: {
        title: '계정 비활성화',
        description: '정말 계정을 비활성화하시겠습니까? 데이터는 보존되지만 접근할 수 없습니다.',
        confirmButton: '비활성화',
        cancelButton: '취소',
        warning: '이 작업은 고객 지원팀에 문의하여 되돌릴 수 있습니다.',
      },
      deleteAccount: {
        title: '계정 삭제',
        description: '정말 계정을 영구적으로 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
        confirmButton: '영구 삭제',
        cancelButton: '취소',
        warning: '모든 데이터, 메시지, 워크스페이스가 영구적으로 삭제됩니다.',
        typeToConfirm: '확인을 위해 "삭제"를 입력하세요',
        confirmPlaceholder: '삭제',
      },
    },
  },
};

export default modalsStrings;
