export const workspaceAdminStrings = {
  en: {
    workspaceAdmin: {
      backToWorkspace: 'Back to workspace',
      navDashboard: 'Overview',
      navMembers: 'Members',
      navInviteManagement: 'Invite management',
      navChannels: 'Channels',
      navGroups: 'Groups',
      navPermissions: 'Permissions',
      navIntegrations: 'Integrations',
      navSecurity: 'Security',
      navAuditLog: 'Audit log',
      navAiAssistant: 'AI assistant',
      navAiSearch: 'AI search',
      dashboardTitle: 'Workspace insights',
      dashboardSubtitle: 'Monitor activity and keep your workspace organised.',
      statMembers: 'Total members',
      statChannels: 'Active channels',
      statMessages: 'Messages today',
      statActiveUsers: 'Active users',
      recentActivity: 'Recent activity',
      workspaceOverviewTitle: 'Workspace profile',
      workspaceOverviewDescription: 'Update the workspace name, description, and visibility.',
      workspaceNameLabel: 'Workspace name',
      workspaceDescriptionLabel: 'Description',
      defaultChannelLabel: 'Default welcome channel',
      autoInviteLabel: 'Auto invite new teammates to default channels',
      twoFactorLabel: 'Require 2FA for admins',
      saveChanges: 'Save changes',
      membersTitle: 'Manage members',
      membersDescription: 'Review roles and invite teammates.',
      membersInviteStatusTitle: 'Invitation status',
      membersInviteStatusDescription: 'Review outstanding workspace invitations and see who has joined.',
      membersInviteStatusEmpty: 'No pending invitations.',
      membersInviteStatusAccepted: 'Accepted',
      membersInviteStatusPending: 'Pending',
      membersInviteStatusExpired: 'Expired',
      membersBlockedTitle: 'Blocked users',
      membersBlockedDescription: 'Suspended or blocked accounts are listed here.',
      membersBlockedEmpty: 'No blocked accounts.',
      membersBlockedUnblock: 'Unblock',
      membersParticipantsTitle: 'Workspace participants',
      membersParticipantsDescription: 'Includes both members and guest accounts.',
      membersExport: 'Export member list',
      membersMoveToGroup: 'Move selected to group',
      membersHistoryTitle: 'Join & leave history',
      membersHistoryDescription: 'Track all workspace membership changes.',
      membersHistoryEmpty: 'No membership changes recorded yet.',
      membersHistoryActionJoin: 'joined the workspace',
      membersHistoryActionLeave: 'left the workspace',
      membersHistoryActionInvited: 'was invited',
      inviteMember: 'Invite member',
      inviteManagementTitle: 'Invite management',
      inviteManagementDescription: 'Track pending invites and manage reusable invite links.',
      inviteManagementPendingTitle: 'Pending invitations',
      inviteManagementLinksTitle: 'Reusable invite links',
      inviteManagementLinksEmpty: 'No active invite links yet.',
      inviteManagementLinkMember: 'Member link',
      inviteManagementLinkGuest: 'Guest link',
      inviteManagementCopy: 'Copy link',
      inviteManagementCopied: 'Copied!',
      inviteManagementLinksDescription: 'Review reusable links shared with teammates or guests.',
      roleOwner: 'Owner',
      roleAdmin: 'Admin',
      roleMember: 'Member',
      permissionsTitle: 'Permission controls',
      permissionsDescription: 'Define who can create channels, invite members, and manage billing.',
      permissionCreateChannels: 'Allow members to create public channels',
      permissionPrivateChannels: 'Allow members to create private channels',
      permissionManageIntegrations: 'Allow admins to manage integrations',
      permissionManageBilling: 'Restrict billing settings to owners only',
      integrationsTitle: 'Connected integrations',
      integrationsDescription: 'Keep tools in sync by managing integrations.',
      integrationsStatusActive: 'Active',
      integrationsStatusPaused: 'Paused',
      integrationsStatusRequest: 'Request access',
      securityTitle: 'Security & compliance',
      securityDescription: 'Enforce workspace policies and retention rules.',
      retentionLabel: 'Message retention (days)',
      auditLogTitle: 'Audit log',
      auditLogDescription: 'Track important actions taken across the workspace.',
      auditViewMore: 'View more logs',
      groupsTitle: 'Group management',
      groupsDescription: 'Create groups and control channel access per group.',
      groupsCreate: 'Create group',
      groupsMembersLabel: 'Members',
      groupsChannelsLabel: 'Channel access',
      groupsAllChannels: 'Workspace channels',
      groupsSave: 'Save changes',
      overview: {
        statsTitle: 'Workspace metrics',
        totalMembers: 'Members',
        totalChannels: 'Channels',
        totalMessages: 'Messages',
        activeToday: 'Active today',
        recentActivity: 'Recent activity',
        noActivity: 'No recent activity.',
      },
    },
  },
  ko: {
    workspaceAdmin: {
      backToWorkspace: '워크스페이스로 돌아가기',
      navDashboard: '개요 대시보드',
      navMembers: '멤버 관리',
      navInviteManagement: '초대 관리',
      navChannels: '채널 관리',
      navGroups: '그룹 관리',
      navPermissions: '권한 설정',
      navIntegrations: '연동 관리',
      navSecurity: '보안 설정',
      navAuditLog: '감사 로그',
      navAiAssistant: 'AI 어시스턴트',
      navAiSearch: 'AI 검색',
      dashboardTitle: '워크스페이스 인사이트',
      dashboardSubtitle: '팀 활동을 모니터링하고 워크스페이스를 정돈하세요.',
      statMembers: '멤버',
      statChannels: '활성 채널',
      statMessages: '오늘 메시지',
      statActiveUsers: '활성 사용자',
      recentActivity: '최근 활동',
      workspaceOverviewTitle: '워크스페이스 정보',
      workspaceOverviewDescription: '워크스페이스 이름, 설명, 기본 설정을 관리합니다.',
      workspaceNameLabel: '워크스페이스 이름',
      workspaceDescriptionLabel: '설명',
      defaultChannelLabel: '기본 환영 채널',
      autoInviteLabel: '새 멤버를 기본 채널에 자동 초대',
      twoFactorLabel: '관리자에게 2단계 인증 요구',
      saveChanges: '변경사항 저장',
      membersTitle: '멤버 관리',
      membersDescription: '역할을 검토하고 팀원을 초대하세요.',
      membersInviteStatusTitle: '초대 상태',
      membersInviteStatusDescription: '발송된 초대와 가입 여부를 확인하세요.',
      membersInviteStatusEmpty: '대기 중인 초대가 없습니다.',
      membersInviteStatusAccepted: '승인됨',
      membersInviteStatusPending: '대기 중',
      membersInviteStatusExpired: '만료됨',
      membersBlockedTitle: '차단된 사용자',
      membersBlockedDescription: '차단되었거나 정지된 계정을 확인할 수 있습니다.',
      membersBlockedEmpty: '차단된 사용자가 없습니다.',
      membersBlockedUnblock: '차단 해제',
      membersParticipantsTitle: '워크스페이스 참여자',
      membersParticipantsDescription: '멤버와 게스트 계정을 모두 포함합니다.',
      membersExport: '멤버 목록 내보내기',
      membersMoveToGroup: '선택한 멤버 그룹 이동',
      membersHistoryTitle: '입장 및 탈퇴 내역',
      membersHistoryDescription: '워크스페이스 멤버십 변동을 모두 확인할 수 있습니다.',
      membersHistoryEmpty: '멤버십 변동 기록이 없습니다.',
      membersHistoryActionJoin: '워크스페이스에 참여했습니다.',
      membersHistoryActionLeave: '워크스페이스를 떠났습니다.',
      membersHistoryActionInvited: '워크스페이스 초대를 받았습니다.',
      inviteMember: '멤버 초대',
      inviteManagementTitle: '초대 관리',
      inviteManagementDescription: '초대 현황을 확인하고 재사용 가능한 초대 링크를 관리하세요.',
      inviteManagementPendingTitle: '대기 중인 초대',
      inviteManagementLinksTitle: '재사용 가능한 초대 링크',
      inviteManagementLinksEmpty: '활성화된 초대 링크가 아직 없습니다.',
      inviteManagementLinkMember: '멤버 초대 링크',
      inviteManagementLinkGuest: '게스트 초대 링크',
      inviteManagementCopy: '링크 복사',
      inviteManagementCopied: '복사됨',
      inviteManagementLinksDescription: '멤버 또는 게스트와 공유 중인 재사용 링크를 확인하세요.',
      roleOwner: '소유자',
      roleAdmin: '관리자',
      roleMember: '멤버',
      permissionsTitle: '권한 제어',
      permissionsDescription: '채널 생성, 초대, 결제 관리를 누가 할 수 있는지 정의합니다.',
      permissionCreateChannels: '멤버가 공개 채널을 생성할 수 있음',
      permissionPrivateChannels: '멤버가 비공개 채널을 생성할 수 있음',
      permissionManageIntegrations: '관리자가 연동을 관리할 수 있음',
      permissionManageBilling: '결제 설정은 소유자만 가능',
      integrationsTitle: '연동 관리',
      integrationsDescription: '외부 도구와의 연동 상태를 확인하고 관리합니다.',
      integrationsStatusActive: '사용 중',
      integrationsStatusPaused: '일시 중지',
      integrationsStatusRequest: '권한 요청',
      securityTitle: '보안 및 컴플라이언스',
      securityDescription: '워크스페이스 정책과 보존 규칙을 적용합니다.',
      retentionLabel: '메시지 보존 기간 (일)',
      auditLogTitle: '감사 로그',
      auditLogDescription: '워크스페이스에서 발생한 주요 작업을 추적합니다.',
      auditViewMore: '로그 더보기',
      groupsTitle: '그룹 관리',
      groupsDescription: '그룹을 생성하고 채널 접근 권한을 설정하세요.',
      groupsCreate: '그룹 생성',
      groupsMembersLabel: '멤버 수',
      groupsChannelsLabel: '채널 접근 권한',
      groupsAllChannels: '워크스페이스 채널',
      groupsSave: '변경사항 저장',
      overview: {
        statsTitle: '워크스페이스 통계',
        totalMembers: '멤버',
        totalChannels: '채널',
        totalMessages: '메시지',
        activeToday: '오늘 활동',
        recentActivity: '최근 활동',
        noActivity: '최근 활동이 없습니다.',
      },
    },
  },
};

export default workspaceAdminStrings;
